project:
  type: website

website:
  title: "Your Site"
  navbar:
    background: light 
    right:
      - icon: rss
        href: index.xml
format:
  html:
    theme: default
    css: styles.css
    toc: true



