project:
  type: website

website:
  title: "Your Site"
  site-url: https://hamelsmu.github.io/minimal-site/
  navbar:
    background: light 
    left:
      - icon: github
        text: See the code
        href: https://github.com/hamelsmu/minimal-site
    right:
      - icon: rss
        href: index.xml
format:
  html:
    theme: default
    css: styles.css
    toc: true



